setup deployment with supabase

diff --git a/.github/workflows/testrun.yaml b/.github/workflows/testrun.yaml
--- a/.github/workflows/testrun.yaml
+++ b/.github/workflows/testrun.yaml
@@ -12,13 +12,9 @@ on:
 
 jobs:
   build:
+    environment: Supabase
     name: Build and Run with Docker Compose
     runs-on: ubuntu-latest
-    env:
-      DB_USERNAME: ${{ vars.DB_USERNAME }}
-      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
-      DB_NAME: ${{ vars.DB_NAME }}
-      DB_URL: ${{ vars.DB_URL }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -32,23 +28,49 @@ jobs:
 
       - name: Clean up Docker environment
         run: docker compose down -v --remove-orphans
-
-      - name: Start database service
-        run: docker compose up test_command_postgres -d
-          
-      - name: Wait for database to be ready
+      
+      - name: Check if all DB secrets are set
+        env:
+          DB_URL: ${{ secrets.DB_URL }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+          DB_USERNAME: ${{ vars.DB_USERNAME }}
         run: |
-          echo "Waiting for database connection..."
-          until docker compose exec -T test_command_postgres pg_isready -U postgres; do
-          sleep 2
-          done
-          echo "Database is ready."
-          
+          missing=""
+          if [ -z "$DB_URL" ]; then
+            echo "DB_URL is not set"
+            missing="yes"
+          fi
+          if [ -z "$DB_PASSWORD" ]; then
+            echo "DB_PASSWORD is not set"
+            missing="yes"
+          fi
+          if [ -z "$DB_USERNAME" ]; then
+            echo "DB_USERNAME is not set"
+            missing="yes"
+          fi
+          if [ -n "$missing" ]; then
+            echo "One or more secrets are missing"
+            exit 1
+          else
+            echo "All DB secrets are set"
+          fi
       - name: Run Flyway migrations
+        env:
+          DB_URL: ${{ secrets.DB_URL }}
+          DB_USERNAME: ${{ secrets.DB_USERNAME }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         run: mvn flyway:migrate
 
       - name: Build application package
+        env:
+          DB_URL: ${{ secrets.DB_URL }}
+          DB_USERNAME: ${{ secrets.DB_USERNAME }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         run: mvn clean package
 
       - name: Build and run all services with Docker Compose
+        env:
+          DB_URL: ${{ secrets.DB_URL }}
+          DB_USERNAME: ${{ secrets.DB_USERNAME }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         run: docker compose up -d --build
